# This workflow will export the modpack into a .zip for curseforge, and publish a new releases.

name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Updated Version E.g. 1.2.10"
        required: true
        
jobs:
  publish:
    name: Publish Modpack Release
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
    
      # Building packwiz, and generating the curseforge export .zip
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Build Packwiz
        run: go install github.com/comp500/packwiz@latest
          
      - name: Generate Release Asset
        run: packwiz cf export
        
      - name: Find Generated Zip
        id: find_zip
        run: echo "::set-output name=zip::Shattered_Stars-${{ github.event.inputs.version }}"
          
      # Publishing the Release https://github.com/marketplace/actions/publish-release
          
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.event.inputs.version }}"
          release_name: "Shattered_Stars-${{ github.event.inputs.version }}"
          body: |
            One Day we'll
            write a changelog
          draft: true
          prerelease: false
          
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_zip.outputs.zip }}.zip
          asset_name: shattered_stars-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
